version: '3'

services:
  data-source:
    build:
      context: ./data-source
    container_name: "data-source"
    networks:
      - app-network
    depends_on:
      - postgres
    ports:
      - "8085:8085"

  cloud:
    build:
      context: ./cloud
    container_name: "cloud"
    networks:
      - app-network
    depends_on:
      - postgres
    ports:
      - "8084:8084"

  document-generator:
    build:
      context: ./document-generator
    container_name: "document-generator"
    networks:
      - app-network
    ports:
      - "8083:8083"

  data-aggregator:
    build:
      context: ./data-aggregator
    container_name: "data-aggregator"
    networks:
      - app-network
    depends_on:
      - rabbitmq
    ports:
      - "8082:8082"

  orchestrator:
    build:
      context: ./orchestrator
    container_name: "orchestrator"
    networks:
      - app-network
    depends_on:
      - rabbitmq
      - data-aggregator
    ports:
      - "8081:8081"

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    container_name: "rabbitmq"
    restart: always
    networks:
      - app-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"

  postgres:
    restart: always
    container_name: "postgres"
    hostname: postgres
    networks:
      - app-network
    image: "postgres:16.1-alpine"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - app-network
    environment:
      - MINIO_ROOT_USER=${MINIO_ASSES_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio

networks:
  app-network:
    driver: bridge

volumes:
  minio-data:
    driver: local
  postgres:
    driver: local