app:
  feign:
    client:
      config:
        print:
          url: http://localhost:8083
        data-source:
          url: http://localhost:8085

logging:
  level:
    com.ebito.data_aggregator: DEBUG
