server:
  port: 8082
  error:
    include-message: always

app:
  feign:
    client:
      config:
        print:
          url: http://document-generator:8083
        data-source:
          url: http://data-source:8085
  rabbitmq:
    queue: ebito_data_aggregator_res_q
    routingkey: ebito_data_aggregator_req_q
    exchange: ebito_exchange

spring:
  application:
    name: data-aggregator
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.ebito.data_aggregator.api.controller.DataAggregatorController: TRACE



