logging:
  level:
    com.ebito.cloud: DEBUG

server:
  port: 8084

spring:
  application:
    name: cloud
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 215MB
  datasource:
    driver-class-name: org.postgresql.Driver
    #    url: ${DB_URL}
    #    username: ${DB_USER}
    #    password: ${DB_PASSWORD}
    url: jdbc:postgresql://rc1a-7hralt7zq1xy378o.mdb.yandexcloud.net:6432/ebito1
    username: ebito
    password: ebitoebito
    testWhileIdle: true
    test-on-borrow: true
    hikari:
      maxLifetime: 60000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
  liquibase:
    change-log: db/changelog/changelog-master.yaml
minio:
  # bucket: ${MINIO_BUCKET}
  # url: ${MINIO_URL}
  # accessKey: ${MINIO_ASSES_KEY}
  # secretKey: ${MINIO_SECRET_KEY}
  bucket: ritschool-storage-2
  url: http://storage.yandexcloud.net
  accessKey: YCAJEmDfIjvb4i1yyBA_-Phzu
  secretKey: YCPgqjf5XryKfPsKbGdmrTqWKOoxppcPvNKP0AcI