apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: ebito-cloud
  labels:
    app-label: ebito-cloud
spec:
  ports:
    - port: 8084
      name: plaintext
      targetPort: 8084
  selector:
    app-label: ebito-cloud
  type: LoadBalancer