apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: ebito-data-aggregator
  labels:
    app-label: ebito-data-aggregator
spec:
  ports:
    - port: 8082
      name: plaintext
      targetPort: 8082
  selector:
    app-label: ebito-data-aggregator
  type: LoadBalancer