apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: ebito-data-source
  labels:
    app-label: ebito-data-source
spec:
  ports:
    - port: 8085
      name: plaintext
      targetPort: 8085
  selector:
    app-label: ebito-data-source
  type: LoadBalancer