apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: ebito-orchestrator
  labels:
    app-label: ebito-orchestrator
spec:
  ports:
    - port: 8081
      name: plaintext
      targetPort: 8081
  selector:
    app-label: ebito-orchestrator
  type: LoadBalancer