server:
  port: 8083

app:
  feign:
    client:
      config:
        cloud:
          url: "http://cloud:8084"

spring:
  application:
    name: document-generator
  main:
    allow-bean-definition-overriding: true

