app:
  feign:
    client:
      config:
        cloud:
          url: "http://localhost:8084"
        data-aggregator:
          url: "http://localhost:8082"

logging:
  level:
    com.ebito.orchestrator: DEBUG